### ISSUE TITLE
Indenting without a vertical bar

### ISSUE THREAD

**Issue by ZarakiKanzaki** [yegor256/naive-ebnf#29]
Hello! I'm trying to use your to formalise a grammar that would look like  a yaml file. The problem is that in order to make it readable I need a way to use some sort of command to insert indentation when i start a new line, for example
``` latex
       <statement> := <A> <new\_line> \\
        \INDENT            <B> <new\_line> \\
```
i don't know if there's a way to do so, could you help me? just to know, A and B should be like more likely
```latex
       <statement> := <A> <new\_line> <B> <new\_line> 
```

but for longer statement i could have problems

**Comment by yegor256** [comment]
@ZarakiKanzaki I think you can try this:

```
\documentclass{minimal}
\usepackage{naive-ebnf}
\begin{document}
\begin{ebnf}
<statement> := <A> \\
  || <B>
\end{ebnf}
\end{document}
```

**Comment by haja-fgabriel** [comment]
I have the same issue with long lines such as:
```TeX
\begin{ebnf}
<ComplexType> := "\char`\<complexType" [ ( " mixed=" <Boolean> ) ] [ ( " name=" <NCName> ) ] "\char`\>" 
( <SimpleContent> | <ComplexContent> | ( [ ( <Group> | <All> | <Choice> | <Sequence> ) ]
{ ( <Attribute> | <AttributeGroup> ) } ) ) "\char`\</complexType\char`\>"
\end{ebnf}
```

**Comment by haja-fgabriel** [comment]
@yegor256 boss, I read the source code and I found a solution that works brilliantly:
just add
```TeX
\\
```
where you want to end the line, and on the new line you add the
```TeX
\makebox[2.6cm][r]{}
```
for indentation (keep in mind that I am using 2.6cm indent, as in `\begin{ebnf}[2.6cm]`

**Comment by haja-fgabriel** [comment]
I propose using a new operator for defining this indent with a vertical bar. For this, I opened #36.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.16`

**Comment by yegor256** [comment]
@ZarakiKanzaki new version 0.0.16 is released to CTAN, thanks to @haja-fgabriel for contribution!
